apiVersion: v1
kind: Service
metadata:
  labels:
    app: span
  name: span
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    app: foo
    tier: backend
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend
